# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

#salesforce configuration
SALESFORCE_USERNAME: "anandcarma@carmatec.in"
SALESFORCE_PASSWORD: "anand4carmatec"
SALESFORCE_SECURITY_TOKEN: "1AxRWTguKX39o5918x0W0OT1"
SALESFORCE_CLIENT_ID: "3MVG9d8..z.hDcPLOxS6A8QddBFKZfhtBWFmXDWyg9Kgf8gkYslH4Y0OrMEpXLH3pTdzxMnkkFtF.Mxl_CTYZ"
SALESFORCE_CLIENT_SECRET: "5272396250281936033"
SALESFORCE_HOST: "ap5.salesforce.com"